# Generated by Django 3.2 on 2022-07-22 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback', models.IntegerField(default=5, help_text='Введите проценты от потраченной суммы')),
                ('is_super', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize1', models.CharField(max_length=50)),
                ('prize2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('name', models.CharField(max_length=120)),
                ('finished_date', models.DateField()),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LotsTicketRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_tickets', models.IntegerField()),
                ('price_tickets', models.IntegerField()),
                ('max_tickets_take', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'AVAILABLE'), ('unavailable', 'UNAVAILABLE')], max_length=15)),
                ('is_winner', models.BooleanField(default=False)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lot.lot')),
            ],
        ),
    ]
