# Generated by Django 3.2 on 2022-07-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
